from langgraph.graph import StateGraph, END
from state import MisinformationState
from tools.search import search_headline
from tools.factcheck import google_fact_check
from tools.alternatives import fetch_alternatives
from tools.extraction import extract_headline
from tools.perplexity import perplexity_verify
from llm import llm

# ------------------ Nodes ------------------

def extract_headline_node(state: MisinformationState):
    # Extract headline if not provided or to ensure accuracy
    extracted = extract_headline(state["article_text"])
    state["headline"] = extracted
    return state


def search_node(state: MisinformationState):
    # Verify presence across sources (search tool returns string, we might just store it)
    # The prompt asks to "Search for the headline... to verify its presence".
    # We store it for potential context, though the decision relies on fact-check.
    state["search_results"] = [search_headline(state["headline"])]
    return state


def fact_check_node(state: MisinformationState):
    result = google_fact_check(state["headline"])
    state["fact_check_result"] = result

    claims = result.get("claims", [])
    
    # Default to UNCERTAIN if no claims found
    if not claims:
        state["verdict"] = "UNCERTAIN"
        state["confidence"] = "50%"
        state["summary"] = "No fact-check data found for this claim."
        return state

    # Parse the first claim
    review = claims[0]["claimReview"][0]
    rating = review.get("textualRating", "").lower()
    
    # Strict Logic
    if any(x in rating for x in ["true", "correct", "accurate"]):
        state["verdict"] = "SAFE TO PROCEED"
        state["confidence"] = "95%" # High confidence in the positive verification
    elif any(x in rating for x in ["false", "incorrect", "fake", "pantsonfire", "lie"]):
        state["verdict"] = "POTENTIAL MISINFORMATION"
        state["confidence"] = "95%" # High confidence that it IS misinformation
    else:
        state["verdict"] = "POTENTIAL MISINFORMATION" 
        state["confidence"] = "70%" # Lower confidence

    return state


def perplexity_check_node(state: MisinformationState):
    """
    Fallback node: Uses Perplexity API to identify obvious facts or fakes
    Specifically useful for post-2024 events/claims.
    """
    headline = state["headline"]
    
    # Use Perplexity tool
    result = perplexity_verify(headline)
    
    verdict = result.get("verdict", "UNCERTAIN")
    summary = result.get("summary", "Analysis failed.")
    
    state["verdict"] = verdict
    state["summary"] = summary
    
    if verdict == "SAFE TO PROCEED":
        state["confidence"] = "90%" # High confidence from Perplexity
    elif verdict == "POTENTIAL MISINFORMATION":
        state["confidence"] = "90%"
    else:
        state["confidence"] = "50%"
        
    return state


def summary_node(state: MisinformationState):
    # Only generate summary if not already generated by fallback
    if not state.get("summary") or state["summary"] == "No fact-check data found for this claim.":
        prompt = f"Give a one-line neutral summary of this article:\n{state['article_text']}"
        state["summary"] = llm.invoke(prompt).content.strip()
    return state


def alternatives_node(state: MisinformationState):
    state["alternatives"] = fetch_alternatives(state["headline"])
    return state


# ------------------ Router ------------------

def route(state: MisinformationState):
    v = state.get("verdict")
    if v == "SAFE TO PROCEED":
        return "safe"
    elif v == "POTENTIAL MISINFORMATION":
        return "misinfo"
    else:
        return "uncertain"

def fact_check_route(state: MisinformationState):
    # If Fact Check found a definitive result, route normally.
    # If UNCERTAIN, try the Perplexity Fallback.
    v = state.get("verdict")
    if v == "UNCERTAIN":
        return "fallback"
    elif v == "SAFE TO PROCEED":
        return "safe"
    else: # POTENTIAL MISINFORMATION
        return "misinfo"

# ------------------ Graph ------------------

builder = StateGraph(MisinformationState)

builder.add_node("extract", extract_headline_node)
builder.add_node("search", search_node)
builder.add_node("fact_check", fact_check_node)
builder.add_node("perplexity_check", perplexity_check_node) # New Fallback Node
builder.add_node("summary", summary_node)
builder.add_node("alternatives", alternatives_node)

builder.set_entry_point("extract")

builder.add_edge("extract", "search")
builder.add_edge("search", "fact_check")

# Route from Fact Check: Safe -> Summary, Misinfo -> Alternatives, Uncertain -> Fallback
builder.add_conditional_edges(
    "fact_check",
    fact_check_route,
    {
        "safe": "summary",
        "misinfo": "alternatives",
        "fallback": "perplexity_check"
    }
)

# Route from Fallback: Safe -> Summary, Misinfo -> Alternatives, Uncertain -> End
builder.add_conditional_edges(
    "perplexity_check",
    route,
    {
        "safe": "summary",
        "misinfo": "alternatives",
        "uncertain": END
    }
)

builder.add_edge("summary", END)
builder.add_edge("alternatives", END)

graph = builder.compile()
